dist: xenial
language: node_js
before_install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
script:
- hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: public
  target-branch: gh-pages
  on:
    branch: master
notifications:
  email: false
env:
  secure: jMHFVHDCzc0WSmnNP6C9KKYVi3uRJrdoDh8DxOjb3/SZGITzT+kkqYh0bEM1TGh8tzAg2PYqSltttmdKGAmQax3Bi0dovQQYf17TX0Nv2ScAXn7qe1JsXlnkhVU7ySAZ1s6t7X4BOE5xBmLmrrTjFqLf0/Omo4KavjviWLreOBu8UjXhx1vuNSsoqvSgXjMEyAWa8mM9qVXIMa3ThkNyMGzwKjQoq2J7gU4XwlcJUBbGnToeGi8HvFijPLNzYR1eR+3aPbdQn1GABic/HUR0glani9fsbO56KhjFjehOlNJDavmEItmJpTiRcRE5JfzlFUad99HilVENGK8uGsSJce9ov8jCyJb0UBh83/4nH1YtAr8FtQOOpc7blcPALXIm6CUjPgUKxj6XOYUcdo0hrNnhgmZa5QMgdR30NR7yr8ZGNvZKuZJ2fuZ9tmdhd5UMwx3lT5jXlcc9+k+EOgJTJrtMaq//3/vA7CQL8wCOaYZs4JPbCwGc7kpKXta7x4U6w59kDQq6sCnStToqNa3a/1YOjxrXW31MGQ7NhDdhc2/M6frDd53NvySFFViKxAg4GOkt0VdW1Br9e1vyEbxC+v44Lg4TShpMejMtA9iiLW03MW8URRcDMeSKnz5PcnF7Rtjm9kgtZsN6l6B1duDP0BTUDfND388IsAKPwkRb2Xs=
