language: bash
before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
script:
  - hugo
notifications:
  email: false
